export data
SocialGouv/monsuivipsy pull request #47
Opened 2020-11-27 17:05 UTC by tangimds

* ⚠️ : put a value in mailFrom varaible in src/export/export.js
 * icons seem to not load correctly in mails

2020-11-30 09:34 UTC, Alezco requested changes

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +const API_USER = '2fbfeec4905f352f871b2590da840571';
A mettre en variable d'environnement ?

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +  const [loading, setLoading] = useState(false);
```suggestion
  const [isLoading, setIsLoading] = useState(false);
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +      const m = await AsyncStorage.getItem(MailStorageKey);
```suggestion
      const storageMail = await AsyncStorage.getItem(MailStorageKey);
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +      if (m) setMail(m);
Mettre des accolades autour des instructions des `if` pour respecter les règles Eslint
```suggestion
      if (storageMail) {
        setMail(storageMail);
      }
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +  var today = new Date();
```suggestion
  const today = new Date();
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +  var firstDay = new Date();
```suggestion
  const firstDay = new Date();
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +    return chartDates.map((date) => {
Retirer le `return` et les acolades

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +  const isChartVisible = (categoryId) => {
Je crois que cette fonction est déjà dans un autre fichier. La mettre dans un fichier `chart-util.js` ?

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +  const formatHtmlTable = () => {
Mettre cette fonction dans un fichier dédié à l'export en lui-même. Elle n'a pas sa place dans le composant qui est dédié uniquement à l'affichage

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +        <link rel="preconnect" href="https://fonts.gstatic.com">
Si possible éviter les appels à Google Fonts pour ne pas avoir de trackers Google

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +        </style>
Pourquoi avoir deux balises `<style>` ? A fusionner si possible

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +          .journal__item-wrapper {
Tout mettre en kebab-case ? `.journal-item-wrapper` ?

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +            const heighest = res.reduce((currentHeigest, current) => {
```suggestion
            const heighest = res.reduce((currentHighest, current) => {
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +            if (!isChartVisible(categoryId)) return '';
Mettre des accolades autour du `return`

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +                    const height = 15 * value + 2;
Pourquoi 15 et 2 ? Mettre ces nombres dans des constantes ou un commentaire pour expliquer ces valeurs

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +                      <ul class="journal__item-symptoms">
Il y a sûrement moyen de refacto ce code pour retourner un JSX en fonction des variables `ANXIETY_FREQUENCE`, `BADTHOUGHTS_FREQUENCE`, etc. Et ensuite, faire un map sur les symptômes.

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +  const formatHtmlTable = () => {
Et aussi, peut-être qu'elle peut être séparée en plusieurs fonctions plus petites

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +        return 'https://monsuivipsy.s3-eu-west-1.amazonaws.com/veryGood.svg';
Pourquoi utiliser S3 plutôt que le dossier assets ?

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +    }).catch((err) => console.log('sendNPS err', err));
```suggestion
    }).catch((error) => console.error('sendNPS error', error));
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +        <Text style={styles.backButton}>{'Retour'}</Text>
```suggestion
        <Text style={styles.backButton}>Retour</Text>
```

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +      {true && (
Est-ce que ce `true` est nécessaire ?

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +      {false && (
Avec ce `false`, ce code ne s'exécute jamais

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +            onChangeText={(txt) => setDays(parseInt(txt))}
```suggestion
            onChangeText={(text => setDays(parseInt(text))}
```

+ Ajouter une fonction pour vérifier que le nombre entré n'est pas négatif ou trop grand

2020-11-30 09:34 UTC, Alezco commented on src/export/export.js
> +            value={'' + days}
```suggestion
            value={days.toString()}
```

2020-12-02 08:45 UTC, Alezco requested changes

2020-12-02 08:45 UTC, Alezco commented on src/export/export.js
> +  onBackPress = navigation.goBack;
```suggestion
  const onBackPress = navigation.goBack;
```

2020-12-02 08:45 UTC, Alezco commented on src/export/export.js
> +    }).catch((err) => console.log('sendNPS err', err));
Appliquer ce retour ?

2020-12-02 08:45 UTC, Alezco commented on src/export/export.js
> +        onPress={this.onBackPress}
Est-ce que ça peut marcher avec juste `onBackPress` ?

2020-12-02 08:45 UTC, Alezco commented on src/export/utils.js
> +      return 'https://monsuivipsy.s3-eu-west-1.amazonaws.com/veryGood.png';
Pourquoi utiliser S3 plutôt que des images du dossier assets ?

2020-12-02 08:45 UTC, Alezco commented on src/export/utils.js
> +  if (!note) return '';
Ajouter des accolades autour du `return`. Il y a un fichier `.eslintrc` à la racine du projet pour que l'IDE/éditeur de texte souligne le code qui ne respecte pas les règles

2020-12-02 08:45 UTC, Alezco commented on src/export/utils.js
> +  var firstDay = new Date();
```suggestion
  const firstDay = new Date();
```

2020-12-02 08:45 UTC, Alezco commented on src/export/utils.js
> +  const computeChartData = (categoryId) => {
Cette fonction est déjà dans `daily-chart.js`, la mettre dans un autre fichier et l'exporter

2020-12-02 08:45 UTC, Alezco commented on src/export/utils.js
> +  const isChartVisible = (categoryId) => {
Cette fonction est dans `calendar.js`, la mettre aussi dans un autre fichier pour l'utiliser à plusieurs endroits

2020-12-02 08:45 UTC, Alezco commented on src/export/utils.js
> +        <link rel="preconnect" href="https://fonts.gstatic.com">
Supprimer les appels à Google Fonts si possible pour éviter les trackers

2020-12-02 08:45 UTC, Alezco commented on src/export/utils.js
> +            if (!isChartVisible(categoryId)) return '';
Mettre des accolades autour du `return`

2020-12-03 08:46 UTC, tangimds commented on src/export/utils.js
> +      return 'https://monsuivipsy.s3-eu-west-1.amazonaws.com/veryGood.png';
Les images sont utilisées dans un doc html, envoyé dans un mail derrière.

2020-12-03 14:25 UTC, Alezco approved these changes

2020-12-03 16:46 UTC, merged